image:
  file: .gitpod.Dockerfile

tasks:
  - before: ./gitpod_before.sh
  - init: ./gitpod_init.sh
  - command: ./gitpod_command.sh

ports:
  - port: 8888
    visibility: private
    onOpen: open-browser
vscode:
  extensions:
    - ms-azuretools.vscode-docker
